<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq3aLA79AgC/BS0BrjV+r'."\n".'9D6H0yw34GeAwY5Bh/mRK0xRy3GbN22dee+xXTe95FZ9F6fwnMbw/ikQqwpgyC9E'."\n".'iG/zvkUXwphjh9L9BWNCcnD9A76aZ8K6J3VA2ReI8LlvhgtGcldsEyMKYohCSLiG'."\n".'uhDR4FVgLk4jKYQ3zWJZrOyolLJLq+V+d/nN7fLb+Ls+apSUj8PFghpVoe8flHui'."\n".'knmZNhiSR7xI1621g3gT2xoWryskdquJ7BGBD+jMmGqefuiuE/D7Sc08/9jfX4Cl'."\n".'310IWosdKG6YXBCJefnxkgthf7Z5H3cEEqdOmxhuC4rp48VXhTAdUIIXncAnaVMp'."\n".'NwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
