<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRn5QD63\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRn5QD63/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRn5QD63.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRn5QD63\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerRn5QD63\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Rn5QD63',
    'container.build_id' => 'de9cc378',
    'container.build_time' => 1733215837,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRn5QD63');
